### ISSUE TITLE
Add support for Vagrant > 1.1.0

### ISSUE THREAD

**Issue by hh** [WinRb/vagrant-windows#21] opened 2013-03-23 03:09 UTC
Looks like the plugin architecture may have changed

**Comment by sneal** [comment] 2013-03-25 15:06
Yeah, the Vagrant plugin architecture has definitely changed. For instance the config object

```
module Vagrant
  module Config
    class Windows < Vagrant::Config::Base
      attr_accessor :winrm_user
```

becomes 

```
class Config < Vagrant.plugin(2, :config)
  attr_accessor :winrm_user
```

There seem to be a lot of changes, but I'd like to get this working since Vagrant 1.1+ is the future and will hopefully mean easier setup and configuration for non-Rubyists.

I'll see how far I can get on the conversion.

**Comment by sneal** [comment] 2013-03-30 05:46
Dupe of https://github.com/BIAINC/vagrant-windows/issues/20

**Comment by pmorton** [comment] 2013-04-26 00:23
@sneal Would you be interested in becoming a comitter?

**Closed as completed by pmorton** 2013-04-26 00:23 UTC

**Comment by sneal** [comment] 2013-04-29 05:07
@pmorton you bet.
