### ISSUE TITLE
Private Networking does not work with virtual box 4.2.12

### ISSUE THREAD

**Issue by jeremyno** [WinRb/vagrant-windows#29] opened 2013-05-01 20:07 UTC
Using the following vagrant file (vagrant 1.1.5, Virtualbox 4.2.12), windows will boot and work as long as the private network line is commented out. Otherwise, I receive a NoMethodError during configure_networks:

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-windows2008r2"
  config.vm.network :private_network, ip: "192.168.33.10"

   config.vm.provider :virtualbox do |vb|
     vb.gui = true
   end

   # Max time to wait for the guest to shutdown
  config.windows.halt_timeout = 15

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # Configure base box parameters
  config.vm.guest = :windows

  # Port forward WinRM and RDP
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985
end
```

``` code
...
[default] Booting VM...
 INFO subprocess: Starting process: ["VBoxManage", "startvm", "b3480617-2908-4405-a02c-2263aada4165", "--type", "gui"]
 INFO interface: info: Waiting for VM to boot. This can take a few minutes.
[default] Waiting for VM to boot. This can take a few minutes.
 INFO machine: guest is windows, using WinRM for communication channel
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "b3480617-2908-4405-a02c-2263aada4165", "--machinereadable"]
 INFO interface: info: VM booted and ready for use!
[default] VM booted and ready for use!
 INFO warden: Calling action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions:0x00000100e97860>
 INFO subprocess: Starting process: ["VBoxManage", "guestproperty", "get", "b3480617-2908-4405-a02c-2263aada4165", "/VirtualBox/GuestAdd/Version"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "b3480617-2908-4405-a02c-2263aada4165", "--machinereadable"]
 INFO interface: info: Configuring and enabling network interfaces...
[default] Configuring and enabling network interfaces...
 INFO machine: Loading guest: windows
 INFO windows: distro_dispatch: windows
 WARN machine: Distro dispatch loop in 'windows'. Exiting loop.
 INFO windows: configure_networks: [{:type=>:static, :adapter_ip=>"192.168.33.1", :ip=>"192.168.33.10", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1}]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "b3480617-2908-4405-a02c-2263aada4165", "--machinereadable"]
ERROR warden: Error occurred: undefined method `[]' for nil:NilClass
 INFO warden: Beginning recovery process...
...
/Users/jnorman/.vagrant.d/gems/gems/vagrant-windows-1.0.0/lib/vagrant-windows/guest/windows.rb:92:in `block in configure_networks': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/jnorman/.vagrant.d/gems/gems/vagrant-windows-1.0.0/lib/vagrant-windows/guest/windows.rb:91:in `each'
    from /Users/jnorman/.vagrant.d/gems/gems/vagrant-windows-1.0.0/lib/vagrant-windows/guest/windows.rb:91:in `configure_networks'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/network.rb:115:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/share_folders.rb:20:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_shared_folders.rb:12:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:11:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/nfs.rb:28:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prune_nfs_exports.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:106:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/provision.rb:45:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/set_name.rb:35:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:37:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:32:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by pmorton** [comment] 2013-05-03 01:46
The issue is manifesting itself here: https://github.com/WinRb/vagrant-windows/blob/master/lib/vagrant-windows/guest/windows.rb#L92. @jenorman Is is possible to have you send the output from a ipconfig /all on the guest?

**Comment by jeremyno** [comment] 2013-05-03 16:15
Since I cannot get the box to stay up if the private network exists, this is from the box without the interface it is trying to configure. (The output is a bit redacted)

``` code
PS C:\Users\vagrant> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : WIN-7DVTQJVSII8
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : xxx.xxx

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : xxx.xxx
   Description . . . . . . . . . . . : Intel(R) PRO/1000 MT Desktop Adapter
   Physical Address. . . . . . . . . : 08-00-27-E2-E2-6B
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::ccc1:5480:609f:9c9a%11(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.0.2.15(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Friday, May 03, 2013 9:02:30 AM
   Lease Expires . . . . . . . . . . : Saturday, May 04, 2013 9:02:30 AM
   Default Gateway . . . . . . . . . : 10.0.2.2
   DHCP Server . . . . . . . . . . . : 10.0.2.2
   DHCPv6 IAID . . . . . . . . . . . : 235405351
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-19-08-CB-F6-08-00-27-E2-E2-6B
   DNS Servers . . . . . . . . . . . : 10.xxx.xxx.xxx
                                       10.xxx.xxx.xxx
                                       10.xxx.xxx.xxx
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.xxx.xxx:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : xxx.xxx
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```

I'm not much of a ruby/vagrant developer, but while investigating, I threw this line before line 92:

``` ruby
@logger.info("network: #{network} vm_interface_map: #{vm_interface_map}")
```

and this is the output (edited for readability)

``` code
INFO windows: 
  network: {:type=>:static, :adapter_ip=>"192.168.33.1", :ip=>"192.168.33.10", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1} 
  vm_interface_map: {"macaddress1"=>{:name=>"Local Area Connection", :mac_address=>"080027E2E26B", :index=>"11"}}
```

**Comment by pmorton** [comment] 2013-05-03 17:17
Confirmed. I am repro this. I am looking into it now.

**Comment by pmorton** [comment] 2013-05-03 17:38
I think I know what is happening here. We go through a discovery routine after we are able to connect to it. However at the point at which we are discovering network interfaces, the OS has not yet installed the network adapters...

**Comment by jeremyno** [comment] 2013-05-03 18:37
I tried to test that hypothesis and am not certain that is the case. I added a sleep 120 before the discovery (https://github.com/WinRb/vagrant-windows/blob/master/lib/vagrant-windows/guest/windows.rb#L70) so I could log in to the gui, run ipconfig /all before the discovery occurs. The relavent ip config info suggests that there are two interfaces, as should be expected:

``` code
Ethernet adapter Local Area Connection 2:

   Description . . . . . . . . . . . : Intel(R) PRO/1000 MT Desktop Adapter #2
   Physical Address. . . . . . . . . : 08-00-27-BF-FE-97
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::b082:83dd:29c4:613c%19(Preferred)
   Autoconfiguration IPv4 Address. . : 169.254.97.60(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 319291431
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-19-08-CB-F6-08-00-27-E2-E2-6B
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : xxx.xxx
   Description . . . . . . . . . . . : Intel(R) PRO/1000 MT Desktop Adapter
   Physical Address. . . . . . . . . : 08-00-27-E2-E2-6B
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::ccc1:5480:609f:9c9a%11(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.0.2.15(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Friday, May 03, 2013 11:22:23 AM
   Lease Expires . . . . . . . . . . : Saturday, May 04, 2013 11:22:23 AM
   Default Gateway . . . . . . . . . : 10.0.2.2
   DHCP Server . . . . . . . . . . . : 10.0.2.2
   DHCPv6 IAID . . . . . . . . . . . : 235405351
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-19-08-CB-F6-08-00-27-E2-E2-6B
   DNS Servers . . . . . . . . . . . : 10.100.21.10
                                       10.140.18.10
                                       10.0.2.2
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

the output of my previous logging piece is (again, formatted for readability):

``` code
INFO windows: configure_networks: [{:type=>:static, :adapter_ip=>"192.168.33.1", :ip=>"192.168.33.10", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1}]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "bfa07152-bd44-4ffc-bb39-9edff93a347d", "--machinereadable"]
 INFO windows: done 
    network: {:type=>:static, :adapter_ip=>"192.168.33.1", :ip=>"192.168.33.10", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1} 
    vm_interface_map: {"macaddress1"=>{:name=>"Local Area Connection", :mac_address=>"080027E2E26B", :index=>"11"}}
```

I could be wrong, but this suggests to me that maybe the discovery process is not finding the interface correctly?

**Comment by pmorton** [comment] 2013-05-03 18:50
I found the problem. Apparently the 4.2 driver does not support read_mac_addresses. This was merged into [4.1](https://github.com/mitchellh/vagrant/blob/v1.1.5/plugins/providers/virtualbox/driver/version_4_1.rb#L326) from one of my earlier pull requests but did not make it into the 4.2 driver. I will create a pull request for this and monkey patch around it for the mean time.

**Comment by pmorton** [comment] 2013-05-03 19:45
@jenorman I just push a fix to master and released on rubygems. Please upgrade and confirm that this is fixed.

**Closed as completed by pmorton** 2013-05-03 19:45 UTC

**Comment by sneal** [comment] 2013-05-03 21:32
@pmorton Thanks for fixing this. I was wondering why 4.2 didn't support read_mac_addresses.

**Comment by jeremyno** [comment] 2013-05-03 21:36
I uninstalled & reinstalled the plugin - version 1.0.1 fixed the issue. Thank you for your help here.
