### ISSUE TITLE
Vagrant 1.2 is not yet supported

### ISSUE THREAD

**Issue by davidpellerin** [WinRb/vagrant-windows#40] opened 2013-05-15 10:14 UTC
It is mentioned in the README that Vagrant 1.2 is not yet supported - but I'm wondering if someone is actively working on this, or if we can start a discussion on what needs to be fixed/changed?

**Comment by sneal** [comment] 2013-05-15 20:10
I'm starting work on [this](https://github.com/WinRb/vagrant-windows/tree/vagrant-1.2) now. I just ran into a Vagrant berkshelf plugin [issue](https://github.com/RiotGames/vagrant-berkshelf/issues/15) which is fixed in Vagrant 1.2.2+.

**Comment by sneal** [comment] 2013-05-16 17:13
Using the vagrant-1.2 branch you can standup a box, but shared folders and thus chef provisioning is broken. I've submitted https://github.com/mitchellh/vagrant/issues/1742

**Comment by stonith** [comment] 2013-06-01 09:44
Tried to get around this by using shell provisioner but the shell provisioner doesn't seem to work.

**Comment by sneal** [comment] 2013-06-03 14:37
I'm thinking we can either further monkey patch the provisioners or wholesale replace the provisioners with Windows specific ones.

**Comment by stonith** [comment] 2013-06-03 15:45
Was trying to find where the shared folder name is specified. Seems it's just the cifs share name tripping up Windows with the subdirectories. If it's just a single folder the paths should work.

**Comment by stonith** [comment] 2013-06-03 18:55
Is it possible to override the SharedFolderNameMachineMapping variable? Remove the /'s or truncate everything past the first /? Would have to override what the Windows guest mounts as well.

**Comment by pmorton** [comment] 2013-06-07 17:24
@sneal Is your plan to support backwards compatibility?

**Comment by sneal** [comment] 2013-06-07 18:33
Hopefully, but I'm not sure how easy that'll be. I think I can just re-expose the capabilities through the existing guest and communicator classes to support Vagrant 1.1.

Right now I'm just trying to get the plugin to work with Vagrant 1.2.2. Hopefully I'll some time next week to work on this more.

**Comment by stonith** [comment] 2013-06-08 08:28
Looks like the SharedFolderNameMachineMapping isn't used for provisioners on windows hosts to windows guests. I was able to get chef-client working and vagrants seems to be copying the required vagrant generated files to /tmp/vagrant-chef-1 which is a permanent folder and not a shared folder mount from virtualbox. On my OSX host I run into the SharedFolderNameMachineMapping issue.

**Comment by stonith** [comment] 2013-06-08 18:48
Also finding winrm really slow to startup after boot of guest. Guest boots to login screen within seconds but winrm doesn't respond for 2min 30min. Starting to think that ssh on the windows guest might be a better way to go.

**Comment by stonith** [comment] 2013-06-09 00:20
Found that WinRM is set to delayed-auto start by default. Sent pull request to add to readme https://github.com/WinRb/vagrant-windows/pull/48

**Comment by sneal** [comment] 2013-06-17 16:15
The vagrant-1.2 branch now properly maps VM shares. Assuming I don't run into any problems using the new plugin today I'll then attempt to make this branch backwards compatible with vagrant 1.1.

**Comment by juliandunn** [comment] 2013-06-17 19:41
@sneal Awesome! Good job!

**Comment by stonith** [comment] 2013-06-17 20:04
@sneal thanks! Confirmed that vagrant share is mapped correctly with Windows host. I'll try my OSX host tonight.

**Comment by sneal** [comment] 2013-06-17 21:29
Branch now supports Vagrant 1.1 and 1.2 on the same code base.

**Comment by davidpellerin** [comment] 2013-06-17 21:31
@sneal Awesome.... can't wait to test this out.

**Comment by stonith** [comment] 2013-06-18 05:02
@sneal works well on OSX. However, hostname changing doesn't seem to work. Never worked for me...

**Comment by davidpellerin** [comment] 2013-06-18 14:16
@sneal I've successfully been able to fire up Windows guests on my Mac OS X machine (10.8.4) running Vagrant 1.2.2.

**Comment by sneal** [comment] 2013-06-18 15:50
@stonith Thanks for trying it out. I've never tried the host renaming, but there was a compilation error in the 1.2 branch earlier in the day around host renaming.

@davidpellerin Glad to hear works, thanks for trying it out!

**Comment by pmorton** [comment] 2013-06-24 22:59
@sneal What about adding some basic tests? Probably time to pay down some technical debt.

**Comment by Sauraus** [comment] 2013-07-09 22:21
Works like a charm for me except for the network config part which I don't care about right now because it defaults to DHCP on the guest OS anyway.

**Comment by colema18** [comment] 2013-08-02 17:19
Sorry for the really dumb question. How do I install the 1.2 version of vagrant-windows? When I do gem install vagrant-windows, I get the 1.0 something version.

**Comment by sneal** [comment] 2013-08-02 17:24
We're waiting for @pmorton to get back from vacation so we can release a new gem. Until then you can build it yourself from the vagrant-1.2 branch.

**Comment by Sauraus** [comment] 2013-08-02 17:31
@colema18 easy :) either fork or clone the git (https://github.com/WinRb/vagrant-windows) repo, switch to the 1.2 branche and build the plugin yourself using Ruby 1.9.3, using 'rake build' and then use [vagrant plugin install 'PATH TO the  plugin you just built']

**Comment by colema18** [comment] 2013-08-02 17:37
Thanks for the quick response sneal (and Sauraus), let me emphasize "really dumb question". I am not sure I am building it right. I navigated to the directory that has the source and did a "bundle install" and it looked like it succedded but also installed vagrant and some other things which scared me a bit because I already have vagrant installed.

I am further concerned I am doing things wrong because the gem doesn't appear in the ruby path/lib/gem folder like it does when I just do the gem install vagrant-windows. If you couldn't tell I am a Microsoft guy and out of my comfort zone with ruby so sorry for the noob questions.

**Comment by Sauraus** [comment] 2013-08-02 17:42
@colema18 did you do 'git checkout vagrant-1.2'?

Also do not run [rake install], only [rake build] this will create the plugin-gem in the pkg direction after which you can run [vagrant plugin install .\pkg\vagrant-windows-1.2.0.gem]

**Comment by colema18** [comment] 2013-08-02 17:50
I have 1.2. Looks like my rake version is too high?

c:\Projects\Win7\vagrant-windows-1.2>rake build
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.0.4. U
sing bundle exec may solve this.
c:/Projects/Win7/vagrant-windows-1.2/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)

(I can delete these comments after i am up and running so I am not cluttering this board for I know it isn't the place for it. thanks for the help)

**Comment by sneal** [comment] 2013-08-02 17:58
bundle install
bundle exec rake
vagrant plugin install pkg/vagrant-windows-1.2.0.gem

**Comment by colema18** [comment] 2013-08-02 19:02
thanks for the help guys, I have it installed now.

**Comment by trlinkin** [comment] 2013-08-05 14:16
Just one more confirmation here... This worked fine for me.

**Comment by sneal** [comment] 2013-08-06 01:39
Closing in favor of PR, issue #71

**Closed as completed by sneal** 2013-08-06 01:39 UTC
Labels: new feature

**Comment by sstarcher** [comment] 2013-08-08 17:17
Tested the current 1.2 branch against Vagrant 1.2.3 - 1.2.7 all seem to have the same error with the puppet money_patch.  Vagrant 1.2.2 seems to be working.
