### ISSUE TITLE
config.winrm.host does not do anything, winrm is still trying to connect to a localhost port

### ISSUE THREAD

**Issue by noahprince22** [WinRb/vagrant-windows#109] opened 2013-10-05 20:24 UTC
I'm using vagrant-windows trying to connect to a bridged vagrant vm. Because it's a bridged connection, the usual method of connecting via a local host port doesn't work. 

On the github readme, it says you can use config.winrm.host to set the guest's IP. I've implemented this in my vagrant file, then ran vagrant with the logger open, and it's still trying to connect to 127.0.0.1 port 5985 (the default). 

My vagrantfile:

```
    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|                                                                                                                 
      config.vm.box = "Windows7"
      config.vm.guest = :windows
      config.windows.halt_timeout = 25
      config.winrm.username = "admin"
      config.winrm.password = "<my password>"
      config.vm.network "public_network"
      config.winrm.host = "192.168.1.78"                                                                                                                                                                    
      config.omnibus.chef_version = :latest
      config.vm.provision :chef_client do |chef|
      chef.chef_server_url = "<my chef url>"
        chef.validation_key_path = "<my validator>"                                                                                                                                                    
      end

    end
```

The output of the logger on vagrant provision:

```
 INFO warden: Calling IN action: #       <Vagrant::Action::Builtin::Provision:0x000000057cfc40>
 INFO warden: Calling IN action: #  <VagrantPlugins::Omnibus::Action::InstallChef:0x000000057e3a38>
 INFO machine: guest is windows, using WinRM for communication channel
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo",     "103270f2-a58a-4939-b2c1-fbd091700a78", "--machinereadable"]
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo",   "103270f2-a58a-4939-b2c1-fbd091700a78", "--machinereadable"]
 INFO winrmfinder: WinRM host: 127.0.0.1
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo",  "103270f2-a58a-4939-b2c1-fbd091700a78", "--machinereadable"]
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 127.0.0.1
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: admin
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED:      Connection refused - connect(2) (http://127.0.0.1:5985)>
```

The connection is refused because it's trying to connect to the computer via a port on LocalHost versus trying to connect via the bridged IP.

**Comment by sneal** [comment] 2013-10-07 21:29
Duplicate of #104

**Closed as completed by sneal** 2013-10-07 21:29 UTC
