### ISSUE TITLE
Private Network fails to Vagrant Up

### ISSUE THREAD

**Issue by ashic** [WinRb/vagrant-windows#61] opened 2013-07-14 03:32 UTC
Here's my set up:
Vagrant: 1.1.5
ruby 1.9.3p374 (2013-01-15) [i386-mingw32]
vagrant-windows (1.0.3) [installed via vagrant plugin install vagrant-windows]
Guest: Win Server 2012 x64
Vitual Box: 4.2.16 r86992

When I do a vagrant up, I get the output below. This seems related to https://github.com/WinRb/vagrant-windows/issues/29 

Is there something obvious I'm missing?

Thanks,
Ashic.

G:\vagrant_test> set VAGRANT_LOG=debug
G:\vagrant_test> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] -- 5985 => 5985 (adapter 1)
[default] -- 1433 => 1433 (adapter 1)
[default] -- 3389 => 3389 (adapter 1)
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
C:/Users/ashic/.vagrant.d/gems/gems/vagrant-windows-1.0.3/lib/vagrant-windows/gu
est/windows.rb:85:in `block in configure_networks': undefined method`[]' for ni
l:NilClass (NoMethodError)
        from C:/Users/ashic/.vagrant.d/gems/gems/vagrant-windows-1.0.3/lib/vagra
nt-windows/guest/windows.rb:84:in `each'
        from C:/Users/ashic/.vagrant.d/gems/gems/vagrant-windows-1.0.3/lib/vagra
nt-windows/guest/windows.rb:84:in`configure_networks'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/network.rb:115:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/share_folders.rb:20:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/clear_shared_folders.rb:12:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/prepare_nfs_settings.rb:11:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/nfs.rb:28:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/prune_nfs_exports.rb:15:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/handle_forwarded_port_collisions.rb:106:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/env_set.rb:19:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/provision.rb:45:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/set_name.rb:35:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/check_accessible.rb:18:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `block in run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/uti
l/busy.rb:19:in`busy'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/call.rb:51:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in`block in run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/uti
l/busy.rb:19:in `busy'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in`run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/call.rb:51:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `block in run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/uti
l/busy.rb:19:in`busy'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/call.rb:51:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/config_validate.rb:25:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/check_virtualbox.rb:17:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/call.rb:57:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builtin/config_validate.rb:25:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/provide
rs/virtualbox/action/check_virtualbox.rb:17:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/warden.rb:34:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/builder.rb:109:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `block in run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/uti
l/busy.rb:19:in`busy'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/act
ion/runner.rb:61:in `run'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/mac
hine.rb:129:in`action'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/command
s/up/command.rb:37:in `block in execute'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plu
gin/v2/command.rb:182:in`block in with_target_vms'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plu
gin/v2/command.rb:180:in `each'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plu
gin/v2/command.rb:180:in`with_target_vms'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/command
s/up/command.rb:32:in `execute'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli
.rb:46:in`execute'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/env
ironment.rb:408:in `cli'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:
in`<top (required)>'
        from D:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23
:in `load'
        from D:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23
:in`<main>'

**Comment by ashic** [comment] 2013-07-14 03:33
I should mention that if I take out the private network bit from the Vagrantfile, then everything runs smoothly.

**Comment by sneal** [comment] 2013-07-29 15:19
This should work, but I can't repro this. I'm using a newer version of vagrant and vagrant-windows. Perhaps you can try this with vagrant1.2+ and the new vagrant-windows plugin when its released in a few days or build it yourself from the vagrant-1.2 branch?

**Comment by usepowershell** [comment] 2013-07-30 14:20
@sneal I get the same error when trying to provision a private network with vagrant-windows 1.2.0 (built this morning) and vagrant 1.2.2.

**Comment by sneal** [comment] 2013-07-30 16:03
Thanks for trying it out, can you try it out again? I added some additional debug logging to the network capability and added a check to ensure the interface isn't nil before attempting to configure it. If it is nil a warning is now logged.

**Comment by usepowershell** [comment] 2013-07-30 16:56
Ok, rebuilt the plugin and vagrant up succeeds, but the IP address is not set on the host only network adapter.

I've pasted the full debug log to https://gist.github.com/smurawski/6114598.

I think the pertinent logging is (but I'm guessing.. very new to ruby and vagrant)..

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG network: Normalized configuration: {:adapter_ip=>"172.28.19.1", :auto_config=>true, :ip=>"172.28.19.30", :mac=>nil
, :netmask=>"255.255.255.0", :nic_type=>nil, :type=>:static, :adapter=>2}
 INFO network: Searching for matching hostonly network: 172.28.19.30
 INFO subprocess: Starting process: ["C:\Program Files\Oracle\VirtualBox\VBoxManage.exe", "list", "dhcpservers"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
IP:             0.0.0.0
NetworkMask:    0.0.0.0
lowerIPAddress: 0.0.0.0
upperIPAddress: 0.0.0.0
Enabled:        No

It looks like it's looking for an adapter on my host with a x.x.x.1 address.  Where would that be configured?  I didn't see any documentation about a convention for that to set up host only networking...

Steve

**Comment by usepowershell** [comment] 2013-07-30 17:06
At least for me, the current patch gets me over the hump, I can pass in a powershell script to configure the ip. :)

**Comment by sneal** [comment] 2013-07-30 19:08
The secondary adapter is missing from the vm_interface_map, which makes me believe that the WQL query is not returning the secondary adapter because its not in the "connected" state; it might be in the "connecting" state or one of the many others.

I've pushed a change to the vagrant 1.2 branch which I hope will fix it. I changed the WQL to query for network adapters to ignore status and instead look for any adapter with a MAC address.

**Comment by usepowershell** [comment] 2013-07-30 19:33
Awesome.  I'll pull it down and give it a spin.

**Comment by usepowershell** [comment] 2013-07-31 19:24
No dice.. To be fair though, my guest is running 2012 R2 Preview.  I'm going to try with some older OS versions.

**Comment by usepowershell** [comment] 2013-08-01 02:52
I've been doing some further testing with the wql method via the winrm gem.  It seems like the problem is there.  No matter what wql is passed, only one hash is returned.

**Comment by sneal** [comment] 2013-08-01 05:35
That's very odd. On my Windows 2008 R2 Server box is will return ~10 adapters if I remove the WHERE clause entirely. Does this seem specific to Windows 2012?

**Comment by usepowershell** [comment] 2013-08-02 02:35
It's due to the WinRM version.. if Windows Management Framework 3 is installed on 2008 R2, I can duplicate the failure.  It looks like the WinRM gem doesn't support wmf 3, which is the default on Server 2012 and available downlevel for Server 2008 and 2008 R2.

**Comment by usepowershell** [comment] 2013-08-02 13:52
I'll submit a pull request in the near future for a workaround.  I'm doing a bit of testing on it now.

**Comment by sneal** [comment] 2013-08-02 15:32
Thanks for digging into this. Upgrading the WinRm gem to 2.0 is on our backlog. Potentially it rectifies this situation? Unfortunately the 2.0 code is sitting in this branch https://github.com/WinRb/WinRM/tree/working

**Comment by usepowershell** [comment] 2013-08-14 20:51
I finally got around to putting in a pull request, sorry for the delay.  Feel free to use that in the gap to working on winrm 2.0.  If it looks like I'll be doing more Ruby, I can try to dig in on the winrm project, but I mainly live in the PowerShell space.

**Comment by georgievrado** [comment] 2013-08-16 11:04
@smurawski 10x for the workaround. I've built the plugin from vagrant-1.2 branch and it properly sets the private network with Windows Management Framework 3.0 installed on 2008R2

**Comment by usepowershell** [comment] 2013-08-16 13:46
@georgievrado Glad I could help.

**Closed as completed** 2013-08-29 00:21 UTC
Labels: bug
